spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drbio_db
    username: drbio_user
    password: drbio_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

file:
  upload-dir: uploads/reports
